#!/usr/bin/env bash
# This script kills all 'nginx' processes changes the listen port to 80
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx start
sudo kill "$(pgrep nginx | head -n1)"
